### ISSUE TITLE
`connectflood` and `chanflood` do not necessarily create concurrent connections

### ISSUE THREAD

**Issue by slingamn** [DanielOaks/irc-stress-test#4]
On my system (running both `oragono` and `ircstress`, with them communicating over loopback TCP), ircstress sends QUIT messages rapidly enough that Oragono only sees a few concurrent connections at a time (as measured by `/proc/${pid}/fd`).

If I comment out the `stress.ETDisconnect` events, I get a better test in terms of pushing Oragono's CPU and RAM limits.

**Comment by DanielOaks** [comment]
Nice, yeah this is definitely a good point.
